artifacts_root: artifacts # Creates artifacts directory in the root folder/repository


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip # Source of dataset in cloud
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion